### ISSUE TITLE
Does it only works on Linux ?

### ISSUE THREAD

**Issue by sbilly** [aojea/netkat#7]
It works fine in Linux, but failed on macOS.

```bash
# go version
go version go1.16.5 darwin/amd64

# go build
package github.com/aojea/netkat
        imports gvisor.dev/gvisor/pkg/tcpip/link/rawfile: build constraints exclude all Go files in /netkat/vendor/gvisor.dev/gvisor/pkg/tcpip/link/rawfile
```

**Comment by aojea** [comment]
hi, sorry , I did miss this comment.
It works in linux only since uses netlink and ebpf that AFAIK are only present on the linux kernel

The error is related to gvisor, maybe that package requires linux, but despite it compiles I don't think it will work out of linux

**Comment by aojea** [comment]
Added to the readme
https://github.com/aojea/netkat/commit/5ec14196172cb66844bd82ffa255cbefea86774c
